import type {
  ApiOperation,
  ApiParameter,
  ApiResponse,
  ApiSchema,
  BilingualText,
} from '@/lib/api-documentation';
import { API_BASE_URL } from '@/lib/api-documentation-base';

// The 'views' group id is registered by the docs coordinator alongside the
// route catalog entries; fragments are written against it ahead of that.
const VIEWS_GROUP: ApiOperation['group'] = 'views';

const text = (en: string, zh: string): BilingualText => ({ en, zh });

const parameter = (
  name: string,
  required: boolean,
  type: string,
  en: string,
  zh: string,
  schema: ApiSchema,
  example: boolean | number | string,
): ApiParameter => ({
  name,
  location: 'query',
  required,
  type,
  description: text(en, zh),
  schema,
  example,
});

const errorSchema: ApiSchema = {
  type: 'object',
  properties: { error: { type: 'string' }, param: { type: 'string' } },
  required: ['error'],
  additionalProperties: true,
};

const lifecyclePointSchema: ApiSchema = {
  type: 'object',
  properties: {
    month: { type: 'number', description: 'Months since the anchor date (model release).' },
    value: { type: 'number', description: 'The selected metric at this point.' },
    revenue: { type: 'number', description: '$/day' },
    cost: { type: 'number', description: '$/day' },
    margin: { type: 'number', description: '$/day' },
    revenuePerMw: { type: 'number', description: '$/MW/day' },
    marginPerMw: { type: 'number', description: '$/MW/day' },
    cumulative: { type: 'number', description: 'Cumulative margin, $' },
    cumulativeRevenue: { type: 'number', description: 'Cumulative revenue, $' },
    isStep: { type: 'boolean' },
    isRamp: { type: 'boolean' },
  },
  required: [
    'month',
    'value',
    'revenue',
    'cost',
    'margin',
    'revenuePerMw',
    'marginPerMw',
    'cumulative',
    'cumulativeRevenue',
    'isStep',
    'isRamp',
  ],
  additionalProperties: false,
};

const seriesSchema: ApiSchema = {
  type: 'object',
  properties: {
    hwKey: { type: 'string', description: 'Base chip key, e.g. b300.' },
    label: { type: 'string' },
    hwKeysUsed: {
      type: 'array',
      items: { type: 'string' },
      description: 'Every config that contributed a rung, in takeover order.',
    },
    disagg: { type: 'boolean' },
    gpus: { type: 'integer' },
    provisionedMw: { type: 'number' },
    costPerHour: { type: 'number' },
    concurrentUsersNow: { type: 'number' },
    availability: { type: 'number' },
    breakEvenPricePerMTok: { type: ['number', 'null'] },
    improvementFactor: { type: ['number', 'null'] },
    improvementCount: { type: 'integer' },
    paybackMonth: { type: ['number', 'null'] },
    lifetimeMargin: { type: 'number' },
    revenuePerDay: { type: 'number' },
    costPerDay: { type: 'number' },
    marginPerDay: { type: 'number' },
    startMonth: { type: 'number' },
    endMonth: { type: 'number' },
    rampEndMonth: { type: ['number', 'null'] },
    points: { type: 'array', items: lifecyclePointSchema },
  },
  required: [
    'hwKey',
    'label',
    'hwKeysUsed',
    'disagg',
    'gpus',
    'provisionedMw',
    'costPerHour',
    'concurrentUsersNow',
    'availability',
    'breakEvenPricePerMTok',
    'points',
  ],
  additionalProperties: true,
};

const responseSchema: ApiSchema = {
  type: 'object',
  properties: {
    view: { type: 'string', enum: ['fleet'] },
    apiVersion: { type: 'string', enum: ['v1'] },
    generatedAt: {
      type: ['string', 'null'],
      description: 'Latest run date among the history rows the view was computed from.',
    },
    params: { type: 'object', additionalProperties: true },
    assumptions: { type: 'object', additionalProperties: true },
    series: { type: 'array', items: seriesSchema },
    count: { type: 'integer' },
  },
  required: ['view', 'apiVersion', 'generatedAt', 'params', 'assumptions', 'series', 'count'],
  additionalProperties: false,
};

const successExample = {
  view: 'fleet',
  apiVersion: 'v1',
  generatedAt: '2026-08-20',
  params: {
    model: 'DeepSeek-V4-Pro',
    sequence: '8k/1k',
    precisions: ['fp4'],
    mw: 100,
    price: 0.42,
    oprice: 1.68,
    ramp: 3,
    cache: 10,
    mtbi: 24,
    recovery: 12,
    horizon: 7,
    metric: 'margin',
    percentile: 'p90',
    gpus: [],
    format: 'json',
  },
  assumptions: {
    target: 35,
    costProvider: 'costh',
    costType: 'total',
    mtbiDays: 24,
    recoveryHours: 12,
    inputPricePerMTok: 0.42,
    outputPricePerMTok: 1.68,
    outputPriceMultiple: 4,
    rampMonths: 3,
    cachedInputPct: 10,
    cacheReadRatio: 1,
    availability: 0.98,
    breakEvenPricePerMTok: 0.42,
    anchorDate: '2026-04-24',
    horizonMonths: 7,
  },
  series: [
    {
      hwKey: 'b300',
      label: 'B300',
      hwKeysUsed: ['b300_sglang'],
      disagg: false,
      gpus: 70921,
      provisionedMw: 99.99,
      costPerHour: 212763,
      concurrentUsersNow: 2500000,
      availability: 0.98,
      breakEvenPricePerMTok: 0.42,
      improvementFactor: 1.33,
      improvementCount: 1,
      paybackMonth: null,
      lifetimeMargin: 0,
      points: [
        {
          month: 1.25,
          value: -1250000,
          revenue: 3860000,
          cost: 5110000,
          margin: -1250000,
          revenuePerMw: 38600,
          marginPerMw: -12500,
          cumulative: -38000000,
          cumulativeRevenue: 117000000,
          isStep: true,
          isRamp: true,
        },
      ],
    },
  ],
  count: 1,
};

const successResponse: ApiResponse = {
  status: '200',
  description: text(
    'One lifecycle economics series per chip: a fixed fleet sized against the power budget, projected across the model’s life with every measured config improvement.',
    '每种芯片一条生命周期经济性序列：按功率预算确定固定集群规模，并沿模型生命周期投影每次实测到的配置改进。',
  ),
  schema: responseSchema,
  example: successExample,
  mediaType: 'application/json',
  alternateRepresentations: [
    {
      mediaType: 'text/csv',
      schema: { type: 'string', description: 'One row per lifecycle point.' },
      example:
        'hwKey,label,month,value,revenue,cost,margin,revenuePerMw,marginPerMw,cumulative,cumulativeRevenue,isStep,isRamp\nb300,B300,1.25,-1250000,3860000,5110000,-1250000,38600,-12500,-38000000,117000000,true,true',
    },
  ],
};

export const operations: ApiOperation[] = [
  {
    id: 'get-fleet-view',
    group: VIEWS_GROUP,
    method: 'GET',
    path: '/api/v1/views/fleet',
    summary: text('Fleet lifecycle economics', '集群生命周期经济性'),
    description: text(
      'Sizes a fixed fleet of each chip against a facility power budget at the default 35 tok/s/user target, then projects revenue, cost, and margin across the model’s life. Each chip follows its measured best-so-far staircase: every run date whose best config beat everything before it becomes a step, rolled out over the ramp. Prices default to the cheapest fleet’s break-even at a 4x output:input ratio.',
      '在默认 35 tok/s/user 目标下，按设施功率预算为每种芯片确定固定集群规模，并沿模型生命周期投影收入、成本与利润。每种芯片沿其实测的最优演进阶梯前进：某一运行日期的最佳配置若超过此前所有配置，即构成一个台阶，并按 ramp 逐步生效。价格默认取最便宜集群的盈亏平衡价，输出:输入价格比固定为 4。',
    ),
    audience: 'public',
    stability: 'beta',
    parameters: [
      parameter(
        'model',
        true,
        'string',
        'Display model name or compare slug.',
        '展示模型名称或对比 slug。',
        { type: 'string' },
        'DeepSeek-V4-Pro',
      ),
      parameter(
        'sequence',
        false,
        'enum',
        'Workload sequence. Accepts 1k/1k, 1k/8k, 8k/1k (or hyphenated forms) and agentic-traces (alias agentic).',
        '负载序列。支持 1k/1k、1k/8k、8k/1k（或连字符形式）以及 agentic-traces（别名 agentic）。',
        { type: 'string', default: '8k/1k' },
        '8k/1k',
      ),
      parameter(
        'precisions',
        false,
        'CSV list',
        'Comma-separated precisions. Omit to auto-select the densest precision in the data.',
        '以逗号分隔的精度列表。省略时自动选择数据中曲线最密的精度。',
        { type: 'string' },
        'fp4',
      ),
      parameter(
        'mw',
        true,
        'number',
        'Facility power budget in MW. Must be greater than 0.',
        '设施功率预算（MW），必须大于 0。',
        { type: 'number', minimum: 0 },
        100,
      ),
      parameter(
        'price',
        false,
        'number',
        'Input token price in $/M tokens. Defaults to the cheapest fleet’s break-even; giving only oprice derives it through the 4x ratio.',
        '输入 token 价格（$/M token）。默认取最便宜集群的盈亏平衡价；只给 oprice 时按 4 倍比例推导。',
        { type: 'number', minimum: 0 },
        0.42,
      ),
      parameter(
        'oprice',
        false,
        'number',
        'Output token price in $/M tokens. Defaults to 4x the input price.',
        '输出 token 价格（$/M token）。默认取输入价格的 4 倍。',
        { type: 'number', minimum: 0 },
        1.68,
      ),
      parameter(
        'ramp',
        false,
        'number',
        'Months for each config rollout to reach full rate.',
        '每次配置上线达到满负荷所需的月数。',
        { type: 'number', default: 3, minimum: 0 },
        3,
      ),
      parameter(
        'cache',
        false,
        'number',
        'Cached-input percentage billed at the cache-read discount. Applies to agentic traces only.',
        '按缓存读取折扣计费的缓存输入百分比。仅适用于 agentic traces。',
        { type: 'number', default: 10, minimum: 0, maximum: 100 },
        10,
      ),
      parameter(
        'mtbi',
        false,
        'number',
        'Mean time between interrupts, in days.',
        '平均中断间隔（天）。',
        { type: 'number', default: 24, minimum: 0 },
        24,
      ),
      parameter(
        'recovery',
        false,
        'number',
        'Recovery time per interrupt, in hours.',
        '每次中断的恢复时间（小时）。',
        { type: 'number', default: 12, minimum: 0 },
        12,
      ),
      parameter(
        'horizon',
        false,
        'number',
        'Projection horizon in months. Defaults to a short tail past the last measured sweep.',
        '投影时长（月）。默认在最后一次实测扫描后再留一小段。',
        { type: 'number', minimum: 0 },
        12,
      ),
      parameter(
        'metric',
        false,
        'enum',
        'Which metric each point’s value field carries.',
        '每个点的 value 字段所对应的指标。',
        {
          type: 'string',
          enum: ['margin', 'marginPerMw', 'revenue', 'revenuePerMw', 'cumulativeRevenue'],
          default: 'margin',
        },
        'margin',
      ),
      parameter(
        'percentile',
        false,
        'enum',
        'Interactivity percentile for agentic traces; fixed sequences use the median.',
        'agentic traces 的交互性分位数；固定序列使用中位数。',
        { type: 'string', enum: ['p75', 'p90'], default: 'p90' },
        'p90',
      ),
      parameter(
        'gpus',
        false,
        'CSV list',
        'Comma-separated hardware keys; matches a full hwKey (b300_sglang) or a base chip (b300).',
        '以逗号分隔的硬件键；可匹配完整 hwKey（b300_sglang）或基础芯片（b300）。',
        { type: 'string' },
        'b300,mi355x',
      ),
      parameter(
        'format',
        false,
        'enum',
        'Response encoding.',
        '响应编码。',
        { type: 'string', enum: ['json', 'csv'], default: 'json' },
        'json',
      ),
    ],
    responses: [
      successResponse,
      {
        status: '400',
        description: text(
          'Invalid or missing parameter. The body names the parameter and, for enums, the allowed values.',
          '参数无效或缺失。响应体给出参数名；枚举类参数还会给出允许的取值。',
        ),
        schema: errorSchema,
        example: {
          error: 'mw is required (facility power budget in MW, > 0)',
          param: 'mw',
        },
        mediaType: 'application/json',
      },
      {
        status: '500',
        description: text('Fleet view failed.', '集群视图构建失败。'),
        schema: errorSchema,
        example: { error: 'Internal server error' },
        mediaType: 'application/json',
      },
    ],
    responseShapeName: 'FleetView',
    curlUrl: `${API_BASE_URL}/api/v1/views/fleet?model=DeepSeek-V4-Pro&mw=100`,
  },
];
