import type { OperatorXStatus } from '@semianalysisai/inferencex-db/operatorx/normalize';

const en = {
  title: 'OperatorX',
  description:
    'Single-operator performance from OperatorX CI runs: each op is timed through the framework layer that serves it, with the kernel the framework chose.',
  source: 'Source',
  run: 'Run',
  pool: 'GPU pool',
  mode: 'Mode',
  allPools: 'All pools',
  allModes: 'All modes',
  timing: 'Timing',
  counters: 'Counters',
  loadingRuns: 'Loading OperatorX runs…',
  loadingRun: 'Loading run results…',
  runsError: 'OperatorX runs are unavailable.',
  runError: 'This run could not be loaded.',
  noRuns: 'No OperatorX runs found.',
  unavailable: 'unavailable',
  requested: 'Requested',
  branch: 'Branch',
  commit: 'Commit',
  created: 'Started',
  cluster: 'System',
  image: 'Image',
  actionsRun: 'GitHub Actions run',
  countersNote:
    'Counters run: every op ran once under a hardware profiler, so latencies are perturbed. Use a timing run for latency.',
  operator: 'Operator',
  testlist: 'Testlist',
  backend: 'Backend',
  status: 'Status',
  all: 'All',
  search: 'Filter by shape, precision, kernel or model',
  results: 'results',
  shape: 'Shape',
  precision: 'Precision',
  model: 'Model',
  kernel: 'Kernel',
  latency: 'Latency',
  tflops: 'TFLOPS',
  graph: 'Graph',
  streams: 'Streams',
  previous: 'Previous',
  next: 'Next',
  page: 'Page',
  noResults: 'No results match these filters.',
  close: 'Close',
  detail: 'Result detail',
  args: 'Op arguments',
  timeline: 'Kernel timeline (median profiled replay)',
  kernels: 'Kernels per call',
  telemetry: 'GPU telemetry during timing',
  backendMeta: 'What the backend chose',
  message: 'Message',
  span: 'span',
  busy: 'busy',
  gap: 'gap',
  overlap: 'overlap',
  stream: 'stream',
  calls: 'calls',
  loadingDetail: 'Loading detail…',
  rawMetrics: 'All stored metrics (JSON)',
  status_ok: 'Measured',
  status_unsupported: 'Unsupported',
  status_error: 'Failed',
  status_missing: 'Missing',
};

type Strings = typeof en;

const zh: Strings = {
  ...en,
  title: 'OperatorX',
  description:
    '来自 OperatorX CI 运行的单算子性能：每个算子都通过实际服务它的框架层计时，并记录框架选择的内核。',
  source: '数据源',
  run: '运行',
  pool: 'GPU 资源池',
  mode: '模式',
  allPools: '全部资源池',
  allModes: '全部模式',
  timing: '计时',
  counters: '计数器',
  loadingRuns: '正在加载 OperatorX 运行…',
  loadingRun: '正在加载运行结果…',
  runsError: 'OperatorX 运行不可用。',
  runError: '无法加载此运行。',
  noRuns: '未找到 OperatorX 运行。',
  unavailable: '不可用',
  requested: '请求',
  branch: '分支',
  commit: '提交',
  created: '开始时间',
  cluster: '系统',
  image: '镜像',
  actionsRun: 'GitHub Actions 运行',
  countersNote: '计数器运行：每个算子在硬件分析器下运行一次，延迟受干扰。请使用计时运行查看延迟。',
  operator: '算子',
  testlist: '测试列表',
  backend: '后端',
  status: '状态',
  all: '全部',
  search: '按形状、精度、内核或模型筛选',
  results: '条结果',
  shape: '形状',
  precision: '精度',
  model: '模型',
  kernel: '内核',
  latency: '延迟',
  graph: '图',
  streams: '流',
  previous: '上一页',
  next: '下一页',
  page: '第',
  noResults: '没有符合筛选条件的结果。',
  close: '关闭',
  detail: '结果详情',
  args: '算子参数',
  timeline: '内核时间线（分析重放的中位数）',
  kernels: '每次调用的内核',
  telemetry: '计时期间的 GPU 遥测',
  backendMeta: '后端的选择',
  message: '信息',
  loadingDetail: '正在加载详情…',
  rawMetrics: '全部存储指标（JSON）',
  status_ok: '已测量',
  status_unsupported: '不支持',
  status_error: '失败',
  status_missing: '缺失',
};

export const STRINGS = { en, zh };
export type OperatorXStrings = Strings;

export function statusLabel(t: Strings, status: OperatorXStatus): string {
  return t[`status_${status}`];
}
