/**
 * Public query allowlists shared by handlers, OpenAPI and coverage tests.
 * Update the matching view docs and skills reference with every selector change.
 */
export const VIEW_QUERY_PARAMS = {
  'cache-reuse': [
    'config',
    'date',
    'gpus',
    'model',
    'percentile',
    'precisions',
    'runId',
    'sequence',
    'tcoBasis',
    'unofficialrun',
  ],
  calculator: [
    'costProvider',
    'costType',
    'costcap',
    'date',
    'format',
    'gpus',
    'hideSkuAboveConfigLimit',
    'mode',
    'model',
    'mw',
    'percentile',
    'precisions',
    'runId',
    'sequence',
    'target',
    'tcoBasis',
    'unofficialrun',
  ],
  collectivex: [
    'activeSeries',
    'kvSeries',
    'swapSeries',
    'backend',
    'epSize',
    'kvOp',
    'kvX',
    'kvY',
    'modes',
    'operation',
    'overlapIsl',
    'pageTokens',
    'percentile',
    'phase',
    'precision',
    'runs',
    'sku',
    'suite',
    'swapDirection',
    'swapLayout',
    'swapMetric',
    'swapPercentile',
    'version',
    'yAxis',
  ],
  compare: ['format', 'gpus', 'model', 'scenario', 'slug', 'tiers', 'variant'],
  'current-inferencex-image': [
    'asOf',
    'frameworks',
    'hardware',
    'model',
    'nodeType',
    'precision',
    'sequence',
    'spec',
  ],
  evaluation: ['unofficialrun', 'benchmark', 'date', 'format', 'gpus', 'model', 'precisions'],
  'first-token': [
    'caps',
    'costProvider',
    'costType',
    'date',
    'gpus',
    'minInteractivity',
    'model',
    'percentile',
    'precisions',
    'runId',
    'sequence',
    'tcoBasis',
    'unofficialrun',
  ],
  fleet: [
    'cache',
    'costProvider',
    'costType',
    'format',
    'gpus',
    'horizon',
    'metric',
    'model',
    'mtbi',
    'mw',
    'oprice',
    'percentile',
    'precisions',
    'price',
    'ramp',
    'recovery',
    'sequence',
    'target',
    'tcoBasis',
  ],
  'gpu-metrics': [
    'artifact',
    'chartView',
    'corrXMetric',
    'corrYMetric',
    'direction',
    'downsample',
    'gpus',
    'metric',
    'runId',
    'sort',
  ],
  'gpu-specs': ['format', 'metric'],
  historical: [
    'deployment',
    'end',
    'extendToDate',
    'format',
    'frameworks',
    'gpus',
    'metric',
    'model',
    'precisions',
    'priceSource',
    'sequence',
    'start',
    'target',
    'tcoBasis',
    'vendors',
  ],
  inference: [
    'allPoints',
    'best',
    'date',
    'dates',
    'deployment',
    'end',
    'format',
    'frameworks',
    'gpus',
    'metric',
    'model',
    'optimal',
    'percentile',
    'power',
    'precisions',
    'priceSource',
    'runId',
    'sequence',
    'spec',
    'start',
    'tcoBasis',
    'unofficialrun',
    'userCosts',
    'userPowers',
    'vendors',
    'xmetric',
    'xmode',
  ],
  operatorx: [
    'backend',
    'cluster',
    'metric',
    'operator',
    'page',
    'precision',
    'runId',
    'shape',
    'status',
  ],
  options: ['format'],
  overview: ['compare', 'engine', 'format', 'hwrows', 'models', 'ref', 'rows', 'tier'],
  'profit-estimator': [
    'cachedInputPrice',
    'costProvider',
    'customCosts',
    'date',
    'dates',
    'end',
    'gpus',
    'inputPrice',
    'labCut',
    'model',
    'outputPrice',
    'percentile',
    'powerBasis',
    'precisions',
    'priceSource',
    'runId',
    'sequence',
    'start',
    'target',
    'tcoBasis',
    'unofficialrun',
    'utilization',
  ],
  'profit-estimator-per-gigawatt': [
    'cachedInputPrice',
    'costProvider',
    'customCosts',
    'date',
    'dates',
    'end',
    'gpus',
    'inputPrice',
    'labCut',
    'model',
    'outputPrice',
    'percentile',
    'powerBasis',
    'precisions',
    'priceSource',
    'runId',
    'sequence',
    'start',
    'target',
    'tcoBasis',
    'unofficialrun',
    'utilization',
  ],
  rankings: ['format', 'kind', 'model', 'scenario'],
  reliability: ['asOf', 'format', 'gpus', 'range'],
  submissions: ['direction', 'limit', 'lines', 'mode', 'offset', 'onChangeOnly', 'search', 'sort'],
  video: [
    'artifact',
    'cell',
    'compare',
    'costs',
    'gpuBasis',
    'page',
    'phase',
    'run',
    'selected',
    'slot',
    'source',
    'view',
    'workload',
    'xAxis',
    'yAxis',
  ],
} as const;
export type ReadonlyView = keyof typeof VIEW_QUERY_PARAMS;

/** Every dashboard route, including hidden/public routes, has an explicit disposition. */
export const DASHBOARD_API_COVERAGE = {
  inference: { view: 'inference' },
  'profit-estimator-per-gigawatt': { view: 'profit-estimator-per-gigawatt' },
  'profit-estimator': { view: 'profit-estimator' },
  evaluation: { view: 'evaluation' },
  historical: { view: 'historical' },
  calculator: { view: 'calculator' },
  fleet: { view: 'fleet' },
  'first-token': { view: 'first-token' },
  'cache-reuse': { view: 'cache-reuse' },
  reliability: { view: 'reliability' },
  'gpu-specs': { view: 'gpu-specs' },
  submissions: { view: 'submissions' },
  operatorx: { view: 'operatorx' },
  collectivex: { view: 'collectivex' },
  'gpu-metrics': { view: 'gpu-metrics' },
  'current-inferencex-image': { view: 'current-inferencex-image' },
  video: { view: 'video' },
  'ai-chart': {
    view: 'inference',
    exclusion:
      'Provider keys, private prompts, and locally generated charts are not public datasets.',
  },
  feedback: {
    exclusion:
      'Private user feedback and its write endpoint are sensitive; no public read projection.',
  },
} as const;
