import profileData from './system-power-model.profiles.json';

export const SYSTEM_POWER_MODEL_REVISION = profileData.modelRevision;
export const SYSTEM_POWER_ASSUMPTIONS = profileData.assumptions;
export const SYSTEM_POWER_PROFILES = profileData.profiles;
export type SystemPowerHardware = keyof typeof SYSTEM_POWER_PROFILES;
export const SUPPORTED_SYSTEM_POWER_HARDWARE = Object.keys(
  SYSTEM_POWER_PROFILES,
) as SystemPowerHardware[];

export interface ChassisPowerEstimate {
  hardware: SystemPowerHardware;
  /** Original measured total for all eight SXM/OAM GPUs in this chassis. */
  measuredGpuWatts: number;
  preFanDcWatts: number;
  fanWatts: number;
  dcWatts: number;
  psuEfficiency: number;
  psuLossWatts: number;
  chassisAcWatts: number;
  facilityWatts: number;
  pue: number;
  modelRevision: string;
  modelPath: string;
}

/** Python round uses ties-to-even; toFixed uses ties-away at exact decimal midpoints. */
function pythonRound(value: number, digits = 1): number {
  const factor = 10 ** digits;
  const lower = Math.floor(value * factor);
  // An exactly representable decimal midpoint has an odd numerator over 2^(digits+1).
  const numerator = value * 2 ** (digits + 1);
  if (Number.isInteger(numerator) && numerator % 2 === 1 && lower % 2 === 0) {
    return lower / factor;
  }
  return Number(value.toFixed(digits));
}

/**
 * Fixed README inference sweep at the pinned revision, for one complete 8-GPU chassis.
 * Profiles are generated by executing the original component models. Only their
 * load-dependent fan curve and PSU interpolation execute here; other components
 * stay fixed at the recorded assumptions. This function does no allocation scaling.
 */
export function estimateChassisPower(
  hardware: string,
  measuredGpuWatts: number,
  pue = SYSTEM_POWER_ASSUMPTIONS.pue,
): ChassisPowerEstimate | null {
  const key = hardware.toLowerCase();
  if (
    !Object.hasOwn(SYSTEM_POWER_PROFILES, key) ||
    !Number.isFinite(measuredGpuWatts) ||
    measuredGpuWatts <= 0 ||
    !Number.isFinite(pue) ||
    pue < 1
  ) {
    return null;
  }
  const canonicalHardware = key as SystemPowerHardware;
  const profile = SYSTEM_POWER_PROFILES[canonicalHardware];
  // Preserve the source's summation order and intermediate component rounding.
  const preFanDc = Object.values(profile.fixedComponentsDcWatts).reduce(
    (sum, watts) => sum + watts,
    pythonRound(measuredGpuWatts),
  );
  const fan = profile.fan;
  const loadFraction = Math.min(1, preFanDc / fan.fullCoolingLoadWatts);
  const pwm = Math.min(
    fan.maxPwm,
    Math.max(fan.minPwm, fan.minPwm + (fan.maxPwm - fan.minPwm) * loadFraction ** fan.exponent),
  );
  const fanWatts = pythonRound(
    fan.electricalGroupsWatts.reduce((sum, watts) => sum + watts * pwm ** 3, 0),
  );
  const dc = preFanDc + fanWatts;
  const psu = profile.psu;
  if (dc > psu.maxDcWatts) return null;

  const fraction = dc / psu.loadSharingCapacityWatts;
  const curve = psu.efficiencyCurve;
  let efficiency = curve[0][1];
  for (let i = 1; i < curve.length; i++) {
    const [x0, y0] = curve[i - 1];
    const [x1, y1] = curve[i];
    if (fraction <= x0) break;
    efficiency = fraction < x1 ? y0 + ((y1 - y0) * (fraction - x0)) / (x1 - x0) : y1;
    if (fraction <= x1) break;
  }
  const ac = pythonRound(dc / efficiency);
  // The Python chassis wrappers apply PUE to the already-rounded PSU AC output.
  const facility = pythonRound(ac + ac * (pue - 1));
  if (!Number.isFinite(facility)) return null;
  return {
    hardware: canonicalHardware,
    measuredGpuWatts,
    preFanDcWatts: pythonRound(preFanDc),
    fanWatts,
    dcWatts: pythonRound(dc),
    psuEfficiency: pythonRound(efficiency, 4),
    psuLossWatts: pythonRound(dc / efficiency - dc),
    chassisAcWatts: ac,
    facilityWatts: facility,
    pue,
    modelRevision: SYSTEM_POWER_MODEL_REVISION,
    modelPath: profile.modelPath,
  };
}
